name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: [7.4, 7.3, 7.2]
                laravel: [6.*, 7.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Setup Redis
                uses: supercharge/redis-github-action@1.1.0
                with:
                    redis-version: 6
                if: ${{ matrix.os == 'ubuntu-latest' }}

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: xdebug

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests with Local driver
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage_local.xml
                env:
                    REPLICATION_DRIVER: local

            -   name: Execute tests with Redis driver
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage_redis.xml
                if: ${{ matrix.os == 'ubuntu-latest' }}
                env:
                    REPLICATION_DRIVER: redis

            -   uses: codecov/codecov-action@v1
                with:
                    fail_ci_if_error: false
                    file: '*.xml'
